"""add hashed_password to users

Revision ID: 671faebc932c
Revises: 003
Create Date: 2026-05-27 01:41:55.511794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671faebc932c'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lawyer_contracts_client_user_id', table_name='lawyer_contracts')
    op.drop_index('ix_lawyer_contracts_lawyer_client', table_name='lawyer_contracts')
    op.drop_index('ix_lawyer_contracts_lawyer_id', table_name='lawyer_contracts')
    op.drop_index('ix_lawyers_status', table_name='lawyers')
    op.drop_index('ix_lawyers_user_id', table_name='lawyers')
    op.create_unique_constraint(None, 'lawyers', ['user_id'])
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_idempotency_key', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_idempotency_key', 'users', ['idempotency_key'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'lawyers', type_='unique')
    op.create_index('ix_lawyers_user_id', 'lawyers', ['user_id'], unique=True)
    op.create_index('ix_lawyers_status', 'lawyers', ['status'], unique=False)
    op.create_index('ix_lawyer_contracts_lawyer_id', 'lawyer_contracts', ['lawyer_id'], unique=False)
    op.create_index('ix_lawyer_contracts_lawyer_client', 'lawyer_contracts', ['lawyer_id', 'client_user_id'], unique=False)
    op.create_index('ix_lawyer_contracts_client_user_id', 'lawyer_contracts', ['client_user_id'], unique=False)
    # ### end Alembic commands ###
